title: "\\pkg{iNZight}: A Graphical User Interface for Democratising Data with \\proglang{R}"
title_short: "\\pkg{iNZight}: A GUI for Democratising Data with \\proglang{R}"
authors:
  - "Tom Elliott [1,2]"
  - "Chris Wild [2]"
  - "Daniel Barnett [2]"
  - "Andrew Sporle [3,2]"
affiliations:
  - "Victoria University of Wellington"
  - "University of Auckland"
  - "iNZight Analytics"
abstract: "Visualisation, exploration, and analysis of data is often inaccessible to many due to high up-front costs of learning the necessary coding skills to get started. \\Glspl{gui} allow inexperienced users to gain access to these activities by removing the need for coding. However, currently available \\proglang{R} \\glspl{gui} require some degree of experience with \\proglang{R} and familiarity with many statistical concepts. \\pkg{iNZight}, a \\gls{gui} written in R, enables both students and researchers to interact with and explore data without the need for code and only minimal statistical knowledge. Generalists in government organisations are also able obtain official statistics for reporting purposes. The tool is designed to be easy to use, with intuitive controls, clever defaults for common tasks and other design features to lower the barriers to entry. \\pkg{iNZight} also provides more complex features for manipulation and analysis of data, and includes some code-writing capabilities for researchers to efficiently generate reproducible outputs, or as a pathway for newcomers to learn the basics of the \\proglang{R} programming environment."
